version: '2'
services:
    twitter:
        build: .
        container_name: "twitter"
        image: debian/latest
        volumes:
            - .:/var/www:rw
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        ports:
            - 27017:27017
        volumes:
          - ./data/db:/data/db
        command: mongod --smallfiles --logpath=/dev/null # --quiet
